name: Prokka Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Prokka
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdb-dev libbio-perl-perl libxml-simple-perl
          wget -O "${{ github.workspace }}/bin/tbl2asn" https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/linux64.tbl2asn.gz
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Test Prokka
        run: |
          prokka --version
          prokka --help
          ! prokka --doesnotexist
          prokka --depends
          prokka --setupdb
          prokka --listdb
          prokka --cpus 2 --outdir asm --prefix asm test/plasmid.fna
          grep '>' asm/asm.fna
          prokka --cleandb
